---
title: "STT 2810 Homepage"
author: ""
date: 'Fall 2015'
output:
  html_document:
    css: asu.css
    highlight: textmate
    theme: readable
---


* The course syllabus is stored in the [`Syllabus`](./Syllabus/STT2810sylFall15.html) directory of the STT 2810 repository.

* Course pacing and assignments are stored in the [`CoursePacing`](./CoursePacing/GenericPacing.html) directory of the STT 2810 repository.


* Materials for *Passion Driven Statistics* assignments are maintained in the [STT2810ClassRepo](https://github.com/STAT-ATA-ASU/STT2810ClassRepo) repository.

* The text *Passion Driven Statistics (Light Weight)* is maintained in the [PDS-Book](https://github.com/alanarnholt/PDS-Book) repository.

* The `R` package `PDS` is maintained in the [PDS](https://github.com/alanarnholt/PDS) repository.

* A version (possibly dated) of *Passion Driven Statistics (Light Weight)* is viewable on [RPubs](http://rpubs.com/arnholt/126376).


* Questions related to PDS materials should be addressed with the [piazza account for STT 2810](https://piazza.com/class/iaawd0uzg2193).


* [Class RStudio Server](https://mathr.math.appstate.edu) (you must be registered in the course to access the server)



## Resources you may find helpful

### John Chambers recounts the history of S and R
[John Chambers recounts the history of S and R](http://blog.revolutionanalytics.com/2014/01/john-chambers-recounts-the-history-of-s-and-r.html)

### R
* [R homepage](http://www.r-project.org/)
* [Download R](http://cran.r-project.org/)
* [RStudio (IDE)](http://rstudio.org/)
* [RStudio (IDE) preview relase](https://www.rstudio.com/ide/download/preview)
* [RStudio Documentation](https://support.rstudio.com/hc/en-us/categories/200035113-Documentation)
* [Quick R (all types of examples)](http://www.statmethods.net/index.html)
* [Roger Peng's Computing for Data Analysis Videos](http://bit.ly/UC5UDc)
* [An Introduction to R](http://cran.r-project.org/doc/manuals/r-release/R-intro.html)
* [*Advanced R Development* by Hadley Wickham](http://adv-r.had.co.nz/)
* [Free Code School intro R Course](https://www.codeschool.com/courses/try-r)
* [swirl](swirlstat.com) "swirl teaches you R programming and data science interactively, at your own pace, and right in the R console"
* [_R Packages_ by Hadley Wickham](http://r-pkgs.had.co.nz/)

### [RStudio Cheat Sheets](https://www.rstudio.com/resources/cheatsheets/)

* RStudio IDE Cheat Sheet
* Shiny Cheat Sheet
* Data Visualization Cheat Sheet
* Package Development Cheat Sheet
* Data Wrangling Cheat Sheet
* R Markdown Cheat Sheet
* R Markdown Reference Guide

### Graphics

* [`ggplot2` documentation](http://docs.ggplot2.org/current/)
* [`ggplot2` Main Page](http://ggplot2.org/)
* [`ggplot2` Book](http://ggplot2.org/book/)
* [Cookbook for R](http://www.cookbook-r.com/Graphs/)
* [Lattice: Multivariate Data Visualization with R - Figures and code](http://lmdvr.r-forge.r-project.org/figures/figures.html)
* [Graph Catalog `ggplot2`](http://shinyapps.stat.ubc.ca/r-graph-catalog/)
* [The Grammar and Graphics of Data Science (Video)](https://www.rstudio.com/resources/webinars/the-grammar-and-graphics-of-data-science/) (58:50)

### Using [`dplyr`](https://cran.r-project.org/web/packages/dplyr/index.html)

* [`dplyr` video1-tutorial](http://www.dataschool.io/dplyr-tutorial-for-faster-data-manipulation-in-r/)
* [`dplyr` video2-tutorial](http://www.dataschool.io/dplyr-tutorial-part-2/)


### Reproducible Analysis

* [`knitr` Homepage](http://yihui.name/knitr/)
* [`knitr` Package Development on GitHub](https://github.com/yihui/knitr)
* [*Reproducible Research with* R/RStudio Development on GitHub](https://github.com/christophergandrud/Rep-Res-Book)
* [CRAN views of Reproducible Analysis](http://cran.r-project.org/web/views/ReproducibleResearch.html)
* [Reproducible Reporting (Video)](https://www.rstudio.com/resources/webinars/reproducible-reporting/) (58:03)

### Markdown
* [Using R Markdown](https://support.rstudio.com/hc/en-us/sections/200149716-R-Markdown)
* [Markdown](http://daringfireball.net/projects/markdown/)
* [Getting started with R Markdown Blog](http://jeromyanglim.blogspot.com.au/2012/05/getting-started-with-r-markdown-knitr.html)
* [R Markdown V2](http://rmarkdown.rstudio.com)
* [Getting started with R Markdown (Video)](https://www.rstudio.com/resources/webinars/getting-started-with-r-markdown/) (1:02:44)
  
### LaTeX  

* [Download LaTeX for Macs (TeXLive)](http://tug.org/mactex/)
* [Download LaTeX for Windows (MikTeX)](http://miktex.org/)
* [More Math into LaTeX](http://www.ctan.org/pkg/math-into-latex-4)
* [Getting started with LaTeX](http://www.tug.org/begin.html)
* [LaTeX Wikipedia](http://en.wikipedia.org/wiki/LaTeX) 
* [Clever help finding LaTeX symbols](http://detexify.kirelabs.org/classify.html)

### Creating Slides with R
* [R Presentations](https://support.rstudio.com/hc/en-us/sections/200130218-R-Presentations)
* [Slidify](http://slidify.org/index.html)

### Git
* [Download Git](http://git-scm.com)
* [GitHub Help Page](https://help.github.com/)
* [Git Tutorials (bitbucket)](https://www.atlassian.com/git/tutorial)
* [Create a Project](http://gitimmersion.com/lab_03.html)
* [Git Cheatsheet](http://www.ndpsoftware.com/git-cheatsheet.html)
* [Free Code School Intro to Git](https://www.codeschool.com/courses/try-git)
* [Pro Git Book](http://git-scm.com/book)
* [Try Git on GitHub](http://try.github.io/levels/1/challenges/1)
* [Phillip Guo's Basic Git and Github tutorials (Three tutorials about 10 minutes each)](http://www.pgbovine.net/git-tutorial.htm)
* [Clone a GitHub Repo with RStudio (Video)](https://www.youtube.com/watch?v=YxZ8J2rqhEM) (5:05)
* [Clone a GitHub Repo with RStudio (Slides)](https://github.com/alanarnholt/Homework-Examples/blob/master/Slides/ForkCloneRStudio.pdf)
* [Collaboration and time travel: version control with git, github and RStudio (Video)](https://www.rstudio.com/resources/webinars/collaboration-and-time-travel-version-control-with-git-github-and-rstudio/) (48:56)

### Using Unix Like Commands
* [Play Terminus to learn basics of the shell](http://web.mit.edu/mprat/Public/web/Terminus/Web/main.html)
* [Phillip Guo's Unix-like command line tutorials (Four tutorials about 10 minutes each)](http://www.pgbovine.net/command-line-tutorial.htm)
* [Michael Stonebank's Unix Tutorial for Beginners](http://www.ee.surrey.ac.uk/Teaching/Unix/)


### Other Interesting Stuff
* [R-bloggers](http://r-bloggers.com)