---
title: "week1"
author: 
date: 
output: html_document
---

This week you will sign-up for free accounts on [GitHub](https://github.com), [Rpubs](https://rpubs.com), and [Shiny](http://www.shinyapps.io). 

When you register for a free individual GitHub account, request a [student discount](https://education.github.com) to obtain a few private repositories as well as unlimited public repositories.  Please use something similar to **first_name_last_name** as your username when you register with GitHub.  For example, my username on GitHub is *alanarnholt*. If you have a popular name such as John Smith, you may need to provide some other distinquishing characteristic in your username.  Please use the same **username** for your accounts on Rpubs and Shiny. 

Once you have a GitHub account, send an email to arnholtat@appstate.edu with a Subject line of **STT 2810 - GitHub Username** and tell me in the body of your email your first name, last name, and your GitHub username.  I will then manually add you as a team member to the repository in the STT2810-SP15 organization that has your name (**Last_name-First_name**).  This repository will be where you store all of your work for this course.  I will also change your repository to a private repository viewable only by members of the course at this time.

This week you will install [Git](http://git-scm.com/downloads), [R](http://cran.r-project.org), [RStudio](http://www.rstudio.com/products/rstudio/download/), [zotero](https://www.zotero.org), and optionally [$LaTeX$](http://www.ctan.org/starter) on your personal computer.

Please follow the excellent advice for [installing Git from Jenny Bryan's STAT 545 course](http://stat545-ubc.github.io/git01_git-install.html).

Please follow the directions for [installing R and RStudio for Jenny Bryan's STAT 545 course](http://stat545-ubc.github.io/block000_r-rstudio-install.html).

Watch the following videos as appropriate:

* [Install R on Mac (2 min)](https://www.youtube.com/watch?v=lJxVRgiX-ik)    
* [Install R for Windows (3 min)](https://www.youtube.com/watch?v=LII6of-5Odw)    
* [Install R and RStudio on Windows (5 min)](https://www.youtube.com/watch?v=eD07NznguA4)         
* [Creating RStudio projects from Github Repos (5 min)](https://www.youtube.com/watch?v=YxZ8J2rqhEM)    
* [Basics of Git and GitHub (51 min)](https://www.youtube.com/watch?v=U8GBXvdmHT4)      
* [RStudio Reproducible Reporting (60 minutes)](https://www.youtube.com/watch?v=U8GBXvdmHT4) 

Read pages 1-25 in Passion Driven Statistics (PDS) and watch all linked videos in PDS.

Test drive RStudio by following the directions from [Jenny Bryan's STAT 545 course](http://stat545-ubc.github.io/git05_first-use-git-rstudio.html).

Select a data set you will work with and update your GitHub repository **README** with your chosen data set.  

Complete the Medical Record Assignment and push your excel spreadsheet to your GitHub account. 

