---
title: "week12"
output: html_document
---

* Read Chapters 13 and 18 in PDS and watch the embedded videos. 
* Read/re-read the documents `StatisticsTemplate.html` in the `/Statistics` folder and `Correlation` in the `/Correlation` folder.
* Work on your poster.

 
* Work on **Correlation/Moderation assignment** pages 84 and 89 PDS
* **Correlation/Moderation assignment** see pages 84 and 89 PDS due NLT 5 PM April 17.  Submit assignment
via [http://www.crowdgrader.org](http://www.crowdgrader.org).  The direct link for the Research Plan Assignment is ()

**Correlation/Moderation assignment** 

This is a continuation of the material submitted for the **Chi Square assignment** submitted in week11.  You should revise your assignment as needed based on peer comments.  I encourage everyone to make an appointment with the writing center and to have the writing center review your current assignment.

**Grading Rubric:**

Does the document have sections that explain the `Purpose of the Study` (0.1), the `Variables` used in the study (0.1), and how the data was managed (0.1)? 

Are there graphs for at least two of the categorical variables? (0.1) Is there a sentence or two describing what the reader is viewing? (0.1)  

Is there either a histogram or density plot of one of the numeric variables proposed in the study? (0.1)

Is there a bivariate graph of the principal constructs the researcher is proposing to study? (0.1)  Is there a sentence or two describing what the reader is viewing? (0.1)

Is there a multivariate graph of the principal constructs the researcher is proposing to study? (0.1) Is there a sentence or two describing what the reader is viewing? (0.1)

Do all graphs have the $x$- and $y$- axes labeled appropriately? (0.1). Do all graphs have descriptive titles? (0.1)

Is there a section for the Correlation assignment describing the two numeric variables the author uses? (0.3)

Is there code and output for computing the correlation coeffiecient? (0.3)

Does the author explain their results following the example on page 85 of PDS? (0.3)

Is there a section for the Moderation assignment describing the potential moderator? (0.3)

Is there code and output for testing the potential moderator?  (0.3)

Does the author explain their results? (graphs should be used in the explanation) (0.3)




