---
title: "World Development Indicators"
author: "Alan T. Arnholt"
date: "Spring 2015"
output: html_document
---

```{r, echo = FALSE, message = FALSE}
knitr::opts_chunk$set(comment = NA, message = FALSE, warning = FALSE, fig.align = "center")
library(dplyr)
library(ggplot2)
```


```{r}
library(WDI)
library(PDS)
WDIsearch("CO2")
MOJ <- WDI(country = "all", indicator = c("EN.ATM.CO2E.PC", "EG.USE.COMM.GD.PP.KD"),
    start = 2010, end = 2010, extra = FALSE, cache = NULL)
head(MOJ)
tail(MOJ)
dim(MOJ)
dim(gapminder)
MOJcom <- inner_join(x = gapminder, y = MOJ)
dim(MOJcom)
MOJsom <- MOJcom %>%
  select(-contains("year")) %>%
  rename(CO2perCapita = EN.ATM.CO2E.PC, EnergyPerGDP = EG.USE.COMM.GD.PP.KD)
head(MOJsom)
MOJleft <- left_join(x = gapminder, y = MOJ)
dim(MOJleft)
head(MOJleft)
MOJleft <- MOJleft %>%
  select(-contains("year")) %>%
  rename(CO2perCapita = EN.ATM.CO2E.PC, EnergyPerGDP = EG.USE.COMM.GD.PP.KD)
head(MOJleft)
```

```{r}
MOJO <- WDI(country = "all", indicator = c("EN.ATM.CO2E.PC", "EG.USE.COMM.GD.PP.KD"),
    start = 1900, end = 2015, extra = FALSE, cache = NULL)
head(MOJO)
tail(MOJO)
ggplot(data = MOJO, aes(x = year, y = EN.ATM.CO2E.PC, color = country)) + 
  geom_point(alpha = 0.8) + 
  theme_bw() + 
  guides(color = FALSE) + 
  labs(y = "CO2 emissions (metric tons per capita)")
```

```{r}
MOJOusa <- subset(MOJO, country == "North America")
ggplot(data = MOJOusa, aes(x = year, y = EN.ATM.CO2E.PC)) + 
  geom_point(alpha = 0.8) + 
  theme_bw() + 
  guides(color = FALSE) + 
  labs(y = "CO2 emissions (metric tons per capita)")
```

```{r}
MOJOmini <- MOJO %>%
  filter(country == c("China", "United States", "Spain"))
head(MOJOmini)
ggplot(data = MOJOmini, aes(x = year, y = EN.ATM.CO2E.PC, color = country)) + 
  geom_point(alpha = 0.8) + 
  theme_bw() + 
  labs(y = "CO2 emissions (metric tons per capita)")
```