---
title: "week8"
output: html_document
---

* Read Chapter 9 PDS and watch all videos in the chapter

 - [Graphing 2 Video](https://www.youtube.com/watch?v=Yf121fdtjDA&index=55&list=PLDEF0B9CBD27AD37E)
 - [Graphing Rules](https://www.youtube.com/watch?v=JVq2VKib0vw&index=21&list=PLDEF0B9CBD27AD37E)
 - [Common Graphing Mistakes](https://www.youtube.com/watch?v=iY_t31-R_xU&index=25&list=PLDEF0B9CBD27AD37E)
 
* Work on **Bivariate Graphing Assignment / Data Managment** page 52 PDS
* **Bivariate Graphing Assignment / Data Managment** see page 52 PDS due NLT 5 PM February 27.  Submit assignment
via [http://www.crowdgrader.org](http://www.crowdgrader.org).  The direct link for the Research Plan Assignment is (http://www.crowdgrader.org/crowdgrader/venues/view_venue/864)

**Bivariate Graphing Assignment** 

This is a continuation of the material submitted for the **Univariate Graphing Assignment / Data Managment** assignment submitted in week07.  You should revise your assignment as needed from last week and add one bivariate graph of your principal constructs and one one multivariate graph of your principal constructs.

* Grading Rubric:

Does the document have sections that explain the `Purpose of the Study` (0.25), the `Variables` used in the study (0.25), and how the data was managed (0.25)? 

Are there graphs for at least two of the categorical variables? (0.25) Is there a sentence or two describing what the reader is viewing? (0.25)  

Is there either a histogram or density plot of one of the numeric variables proposed in the study? (0.25)

Is there a bivariate graph of the principal constructs the researcher is proposing to study? (0.50)

Is there a multivariate graph of the principal constructs the researcher is proposing to study? (0.50)

Do all graphs have the $x$- and $y$- axes labelled appropriately? (0.25). Do all graphs have descriptive titles? (0.25)
