---
title: "week7"
output: html_document
---

* Read Chapter 8 PDS
* Watch [Graphing 1 Video](https://www.youtube.com/watch?v=7_b6Rd9Vad8&list=PLDEF0B9CBD27AD37E&index=54)
* Work on **Univariate Graphing Assignment / Data Managment** page 46 PDS
* **Univariate Graphing Assignment / Data Managment** see page 46 PDS due NLT 5 PM February 27.  Submit assignment
via [http://www.crowdgrader.org](http://www.crowdgrader.org).  The direct link for the Research Plan Assignment is (https://www.crowdgrader.org/crowdgrader/venues/view_venue/848).

* Grading Rubric for **Univariate Graphing Assignment/ Data Managment** 

Does the document have sections that explain the `Purpose of the Study` (0.25), the `Variables` used in the study (0.25), and how the data was managed (0.25)? 

Have the variables proposed for use in the project been labeled and renamed? (0.25)

Are there graphs for at least two of the categorical variables? (0.25) Is there a sentence or two describing what the reader is viewing? (0.25)  Have the `x-` and `y-` axes been labeled appropriately? (0.25)

Is there either a histogram or density plot of one of the numeric variables proposed in the study? 0.5

When describing the distribution of the reported histogram or density plot, does the author describe the shape (0.25) and use appropriate statistics to characterize the center (0.25) and spread (0.25)?